#pragma once

namespace Quertz
{
enum class Operator
{
	INVALID,
	EQUAL,EQUAL_GREATER,EQUAL_LOWER,
	GREATER,LOWER,NOT_EQUAL,
	SET,SET_ADD,SET_SUB,SET_MUL,SET_DIV,
	ADD,SUB,MUL,DIV,
	MEMBER,PTR_MEMBER,STATIC_MEMBER,
	PTR,
	ARRAY_START,ARRAY_END,BODY_START,BODY_END,
	SEPERATOR
};
}